version: '3'

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./add/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  backend:
    build: ./add/go-flow
    environment:
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
      - shared-volume:/app-backend

  ml:
    build:
        context: ./
        dockerfile: ./add/ml-flow/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - backend
    volumes:
      - shared-volume:/app-ml

  frontend:
    build:
      context: ./app/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./app:/app
    command: npm start

volumes:
  shared-volume: {}
